/*
 * This file is generated by jOOQ.
 */
package eu.dissco.disscomasschedulerservice.database.jooq;


import eu.dissco.disscomasschedulerservice.database.jooq.tables.MachineAnnotationService;
import eu.dissco.disscomasschedulerservice.database.jooq.tables.MasJobRecord;
import eu.dissco.disscomasschedulerservice.database.jooq.tables.records.MachineAnnotationServiceRecord;
import eu.dissco.disscomasschedulerservice.database.jooq.tables.records.MasJobRecordRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MachineAnnotationServiceRecord> MACHINE_ANNOTATION_SERVICES_PKEY = Internal.createUniqueKey(MachineAnnotationService.MACHINE_ANNOTATION_SERVICE, DSL.name("machine_annotation_services_pkey"), new TableField[] { MachineAnnotationService.MACHINE_ANNOTATION_SERVICE.ID }, true);
    public static final UniqueKey<MasJobRecordRecord> MAS_JOB_RECORD_PK = Internal.createUniqueKey(MasJobRecord.MAS_JOB_RECORD, DSL.name("mas_job_record_pk"), new TableField[] { MasJobRecord.MAS_JOB_RECORD.JOB_ID }, true);
}
