/*
 * This file is generated by jOOQ.
 */
package eu.dissco.disscomasschedulerservice.database.jooq;


import eu.dissco.disscomasschedulerservice.database.jooq.tables.MachineAnnotationService;
import eu.dissco.disscomasschedulerservice.database.jooq.tables.MasJobRecord;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.machine_annotation_service</code>.
     */
    public static final MachineAnnotationService MACHINE_ANNOTATION_SERVICE = MachineAnnotationService.MACHINE_ANNOTATION_SERVICE;

    /**
     * The table <code>public.mas_job_record</code>.
     */
    public static final MasJobRecord MAS_JOB_RECORD = MasJobRecord.MAS_JOB_RECORD;
}
